# Generated by Django 4.2 on 2023-05-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0002_event_schedule_remove_actividad_no_fija_usuario_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='constraints',
            field=models.JSONField(default=dict),
        ),
    ]
