# Generated by Django 4.2 on 2023-05-09 23:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('horario', '0003_event_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(7))),
                ('hour', models.IntegerField(verbose_name=django.core.validators.MaxValueValidator(24))),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='fixed',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(default='actividad_fija', max_length=50),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.AddField(
            model_name='position',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario.event'),
        ),
        migrations.AddField(
            model_name='position',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
